#!/usr/bin/env bash
# while loops that prints 10 Best School and hi then Best School

i=0
while [ $i -le 9 ]
do
  if [ $i -eq 8 ]
  then
      echo "Hi"
  else
      echo "Best School"
  fi
  ((i++))
done 
