#!/usr/bin/env bash
#printing number from 1 - 20

i=0
while [ $i -le 20 ]
do
    case $i in

        4)
	    echo $i
	    echo 'bad luck from China'
	;;

        9)
	    echo $i
	    echo 'bad luck from Japan'
	;;

  	17)
	    echo $i
	    echo 'bad luck from Italy'
	;;

	*)
	    echo $i

	esac

	((i++))
done
